CREATE TABLE "USERS" (
	"USERNAME"   VARCHAR2(100 CHAR) NOT NULL,
	"PWD"        VARCHAR2(100 CHAR),
	"FIRST_NAME" VARCHAR2(100 CHAR),
	"LAST_NAME"  VARCHAR2(100 CHAR),
	"EMAIL"      VARCHAR2(100 CHAR),
	PRIMARY KEY ("USERNAME")
)

CREATE TABLE "BLOG" (
	"ID"          VARCHAR2(100 CHAR) NOT NULL,
	"NAME"        VARCHAR2(100 CHAR),
	"DESCRIPTION" VARCHAR2(200 CHAR),
	"OWNER"       VARCHAR2(100 CHAR),
	"CREATED_AT"  DATE,
	"UPDATED_AT"  DATE,
	PRIMARY KEY ("ID")
)

CREATE TABLE "POST" (
	"ID"         VARCHAR2(100 CHAR) NOT NULL,
	"BLOG_ID"    VARCHAR2(100 CHAR),
	"TITLE"      VARCHAR2(200 CHAR),
	"AUTHOR"     VARCHAR2(100 CHAR),
	"CREATED_AT" DATE,
	"UPDATED_AT" DATE,
	"CONTENT"    CLOB,
	PRIMARY KEY ("ID")
)

CREATE TABLE "COMMENTS" (
	"ID"         VARCHAR2(100 CHAR) NOT NULL,
	"POST_ID"    VARCHAR2(100 CHAR),
	"AUTHOR"     VARCHAR2(100 CHAR),
	"CREATED_AT" DATE,
	"CONTENT"    VARCHAR2(1000 CHAR),
	PRIMARY KEY ("ID")
)